name: Generate Metrics SVG
on:
 schedule:
  - cron: "0 0 1/5 * *"
 workflow_dispatch:
 push:
  branches: main

jobs:
 generate:
  runs-on: ubuntu-latest
  permissions:
   contents: write
  steps:
   - uses: lowlighter/metrics@latest
     with:
      token: ${{ secrets.METRICS_TOKEN }}
      user: freitaseric
      template: terminal
      base: header, activity, repositories, metadata
      config_timezone: America/Manaus
      plugin_languages: yes
      plugin_languages_analysis_timeout: 15
      plugin_languages_analysis_timeout_repositories: 7.5
      plugin_languages_categories: markup, programming
      plugin_languages_colors: github
      plugin_languages_ignored: TSQL, PLSQL
      plugin_languages_limit: 8
      plugin_languages_recent_categories: markup, programming
      plugin_languages_recent_days: 14
      plugin_languages_recent_load: 300
      plugin_languages_sections: most-used
      plugin_languages_threshold: 0%
      plugin_repositories: yes
      plugin_repositories_order: featured, pinned, starred, random
      plugin_repositories_pinned: 6
      plugin_repositories_starred: 3
      plugin_stargazers: yes
      plugin_stargazers_charts_type: classic
      plugin_stargazers_days: 9999
      plugin_stargazers_worldmap: yes
